services:
  frontpage:
    image: hiquest/frontpage:latest
    ports:
      - "3043:3043"
    volumes:
      - ~/.frontpage:/data/frontpage
    environment:
      - NODE_ENV=production
      - MT_HOME=/data/frontpage
      - ANTHROPIC_API_KEY=yourkey
      - OPENROUTER_API_KEY=yourkey
    restart: unless-stopped
